version: '3'
services:
  app: &app
    build: 
      context: .
      dockerfile: ./Dockerfile_dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/app/:cached
      - bundle:/usr/local/bundle
    depends_on:
      - database
    ports:
      - 3008:3000
    tty: true
    stdin_open: true
    environment:
      TERM: dumb
      DATABASE_URL: postgres://postgres:@database:5432
      RAILS_ENV: development
  database:
    image: postgres:12.3-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5439:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  bundle:
  database:
