default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  port: 5439

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  port: 5432
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
